version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_gestao
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gestao_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_local

  web:
    build: ./app
    container_name: flask_gestao
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - rede_local

volumes:
  postgres_data:

networks:
  rede_local: